@echo off
echo Cleaning environment for V3...
rd /s /q node_modules
del /f package-lock.json
echo Installing core routing engine...
npm install react-router-dom --save
echo Installing other dependencies...
npm install
