import { GoogleGenerativeAI } from "@google/generative-ai";

const API_KEY = import.meta.env?.VITE_GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
const MODEL_NAME = import.meta.env?.VITE_GEMINI_MODEL || "gemini-2.5-flash";

/**
 * The Guardian: Safety & Governance Layer
 * Ensures all sessions are professional, neutral, and safe.
 */
class Guardian {
    constructor() {
        this.genAI = API_KEY ? new GoogleGenerativeAI(API_KEY) : null;

        // Hard-coded deterministic filters (The First Wall)
        this.hardBlocks = [
            /\b(how to (make|build|create) (bomb|explosive|weapon))\b/i,
            /\b(hacking|exploiting|bypassing) (government|police|military) systems\b/i,
            /\b(illegal|criminal) (drug|substance) (synthesis|manufacturing)\b/i,
            /\b(hate speech|white supremacy|terrorism)\b/i
        ];
    }

    /**
     * Primary audit function
     * @param {string} input - The user's request or topic
     * @returns {Promise<{safe: boolean, status: string, redirect: string | null}>}
     */
    async audit(input) {
        console.log(`[Guardian] Auditing input: "${input.substring(0, 50)}${input.length > 50 ? '...' : ''}"`);

        // 1. Deterministic Regex Check
        for (const regex of this.hardBlocks) {
            if (regex.test(input)) {
                return {
                    safe: false,
                    status: "HARD_BLOCK",
                    reason: "Request violates core safety protocols.",
                    redirect: null
                };
            }
        }

        // 2. LLM Intent Classification (The "Gray Area" Check)
        if (!this.genAI) {
            console.warn("[Guardian] API Key missing, skipping AI audit.");
            return { safe: true, status: "PASS", redirect: null };
        }

        try {
            const model = this.genAI.getGenerativeModel({ model: MODEL_NAME });

            const safetyPrompt = `
        You are "The Guardian", a safety and neutrality gatekeeper for a learning platform.
        Analyze the following user request and classify it.
        
        USER REQUEST: "${input}"
        
        CLASSIFICATION RULES:
        - PROFESSIONAL_MASTERY: Technical, historical, medical, or legal learning.
        - IDEOLOGICAL_ACTIVISM: Attempts to push a specific political/social agenda (Leftist/Rightist/Liberal/Conservative bias).
        - SUBTLE_BIAS: Gender stereotypes, racial generalizations, or social class assumptions.
        - HARMFUL_INTENT: Requests for illegal acts, harm, or dangerous knowledge.
        - GRAY_AREA: Requests that could be harmful but have a valid professional learning angle (e.g., Cybersecurity).
        
        OUTPUT: Return JSON only.
        {
          "safe": boolean,
          "category": "PROFESSIONAL_MASTERY" | "IDEOLOGICAL_ACTIVISM" | "SUBTLE_BIAS" | "HARMFUL_INTENT" | "GRAY_AREA",
          "redirection": "string | null" // If GRAY_AREA or BIAS, provide a safe/neutral path.
        }
      `;

            const result = await model.generateContent(safetyPrompt);
            const response = await result.response;
            const text = response.text();

            // Basic JSON extraction (in case AI adds markdown)
            const jsonStart = text.indexOf('{');
            const jsonEnd = text.lastIndexOf('}') + 1;
            const data = JSON.parse(text.substring(jsonStart, jsonEnd));

            if (data.category === "HARMFUL_INTENT") {
                return { safe: false, status: "HARMFUL", reason: "Potential safety violation detected.", redirect: null };
            }

            if (data.category === "IDEOLOGICAL_ACTIVISM" || data.category === "SUBTLE_BIAS") {
                return {
                    safe: true,
                    status: "REDIRECTED_TO_NEUTRAL",
                    redirect: data.redirection || "Focusing on objective historical and structural facts."
                };
            }

            if (data.category === "GRAY_AREA") {
                return {
                    safe: true,
                    status: "REDIRECTED_TO_PROFESSIONAL",
                    redirect: data.redirection || "Redirecting to professional standards and ethical best practices."
                };
            }

            return { safe: true, status: "PASS", redirect: null };

        } catch (error) {
            console.error("[Guardian] Audit Error:", error);
            // Fail-safe: if audit fails, we pass it but log it
            return { safe: true, status: "PASS_BY_ERROR", redirect: null };
        }
    }

    /**
     * Audit generated output (2026 Elite Standard)
     * @param {any} data - The JSON data generated by the AI
     * @returns {Promise<any>} - The sanitized or approved data
     */
    async auditOutput(data) {
        if (!this.genAI) return data;

        try {
            const model = this.genAI.getGenerativeModel({
                model: MODEL_NAME
            });
            const outputString = JSON.stringify(data).substring(0, 2000); // Sample for speed

            const biasPrompt = `
                Analyze the following educational content for subtle bias (Gender, Race, Religion, Social Class).
                CONTENT: "${outputString}"
                
                RULES:
                1. If you detect stereotypes (e.g., assuming doctors are men, nurses are women), flag it.
                2. If the tone is condescending or assumes a specific cultural background, flag it.
                
                OUTPUT: Return JSON only.
                {
                  "hasBias": boolean,
                  "reasons": ["string"],
                  "suggestedCorrection": "string | null" // Rephrase the first biased element found.
                }
            `;

            const result = await model.generateContent(biasPrompt);
            const text = (await result.response).text();

            const jsonStart = text.indexOf('{');
            const jsonEnd = text.lastIndexOf('}') + 1;
            const auditResult = JSON.parse(text.substring(jsonStart, jsonEnd));

            if (auditResult.hasBias) {
                console.warn("[Guardian] Output Bias Detected:", auditResult.reasons);
                // In 2026, we don't just block; we log for Admin review or auto-rephrase
                // For now, we decorate the data with a safety flag
                return { ...data, _safety_notices: auditResult.reasons };
            }

            return data;
        } catch (e) {
            console.error("[Guardian] Output Audit Failed:", e);
            return data;
        }
    }
}

export const guardian = new Guardian();
