import { create } from 'zustand';
import { generateLiveQuiz as generateGeminiQuiz } from '../services/geminiService';
import { loginWithGoogle, logout, subscribeToAuthChanges, registerWithEmail, loginWithEmail } from '../services/authService';
import { saveUserStats, syncSessionData, getUserStats, saveQuizToHistory, getQuizFromVault, saveQuizToVault, saveUsageStats, getSavedQuizzes, saveQuizToUserVault } from '../services/dbService';
import { guardian } from '../services/Guardian';

export const useStore = create((set, get) => ({
    // User State
    user: null,
    role: 'learner', // Default: learner | moderator | admin
    isAuthLoading: true,

    // Quiz State
    currentQuiz: JSON.parse(localStorage.getItem('quiz_data')) || [],
    currentQuestionIndex: parseInt(localStorage.getItem('quiz_index')) || 0,
    score: parseInt(localStorage.getItem('quiz_score')) || 0,
    answers: JSON.parse(localStorage.getItem('quiz_answers')) || [],
    userTopic: localStorage.getItem('quiz_topic') || '',
    isGenerating: false,
    currentDifficulty: localStorage.getItem('quiz_diff') || 'Intermediate',
    isScenarioMode: JSON.parse(localStorage.getItem('is_scenario_mode')) || false,

    // Vault State
    savedQuizzes: [],
    currentFlashcards: null,

    skillStats: {
        Syntax: 0,
        Architecture: 0,
        Logic: 0,
        Theory: 0,
        Security: 0
    },

    globalStats: JSON.parse(localStorage.getItem('global_stats')) || {
        totalQuizzes: 0,
        averageScore: 0
    },

    // Improvement Room State
    isForgeActive: false,
    forgeConcept: null,
    forgeStep: 1, // 1: Basics, 2: Simple Example, 3: Final Check
    forgeData: null,

    // Roadmap Progress: { roadmapId: [completedNodeIds] }
    roadmapProgress: JSON.parse(localStorage.getItem('roadmap_progress')) || {},
    roadmapLevels: JSON.parse(localStorage.getItem('roadmap_levels')) || {},
    activeRoadmapId: localStorage.getItem('active_roadmap_id') || null,
    activeRoadmapNode: localStorage.getItem('active_roadmap_node') || null,

    // Usage Tracking
    usageStats: JSON.parse(localStorage.getItem('usage_stats')) || {
        roadmapsGenerated: 0,
        quizzesGeneratedToday: 0,
        lastQuizDate: new Date().toDateString()
    },
    isPremium: JSON.parse(localStorage.getItem('is_premium')) || false,
    customRoadmaps: JSON.parse(localStorage.getItem('custom_roadmaps')) || [], // Roadmaps generated by user

    updatePremiumStatus: async (status) => {
        const { user } = get();
        if (!user) return;

        try {
            await saveUsageStats(user.uid, { isPremium: status });
            set({ isPremium: status });
            localStorage.setItem('is_premium', JSON.stringify(status));
        } catch (error) {
            console.error("Store: Premium Update Failed", error);
        }
    },

    setUsageStats: (newStats) => {
        set({ usageStats: newStats });
        localStorage.setItem('usage_stats', JSON.stringify(newStats));
    },

    getWeakSectors: () => {
        const stats = get().skillStats;
        const sectors = Object.keys(stats);
        const minVal = Math.min(...Object.values(stats));
        // Return sectors that are at the minimum level if there's significant variance
        if (Math.max(...Object.values(stats)) === 0) return [];
        return sectors.filter(s => stats[s] === minVal);
    },

    // Actions
    fetchSavedQuizzes: async () => {
        const { user } = get();
        if (!user) return;
        try {
            const quizzes = await getSavedQuizzes(user.uid);
            set({ savedQuizzes: quizzes });
        } catch (error) {
            console.error("Failed to fetch saved quizzes", error);
        }
    },

    saveCurrentQuiz: async (title) => {
        const { user, currentQuiz, userTopic, currentDifficulty } = get();
        if (!user || currentQuiz.length === 0) return false;

        try {
            const quizData = {
                title: title || userTopic || 'Untitled Quiz',
                topic: userTopic,
                difficulty: currentDifficulty,
                questions: currentQuiz,
                createdAt: new Date().toISOString()
            };
            await saveQuizToUserVault(user.uid, quizData);
            await get().fetchSavedQuizzes(); // Refresh the list
            return true;
        } catch (error) {
            console.error("Failed to save quiz", error);
            return false;
        }
    },

    loadQuizToFlashcards: (quizId) => {
        const { savedQuizzes } = get();
        const quiz = savedQuizzes.find(q => q.id === quizId);
        if (quiz) {
            set({ currentFlashcards: quiz.questions });
            return true;
        }
        return false;
    },

    generateFlashcardsFromTopic: async (topic, difficulty = 'Intermediate') => {
        set({ isGenerating: true });

        try {
            // Setup naming logic identical to generic quiz generation
            let activeTopic = topic;
            if (activeTopic.startsWith("Mastery: ")) activeTopic = activeTopic.replace("Mastery: ", "");

            // 1. Try to hit the Knowledge Vault (Cache) first
            const cachedQuiz = await getQuizFromVault(activeTopic, difficulty);
            if (cachedQuiz) {
                console.log(`[Store:Flashcards] Vault Hit: ${activeTopic}`);
                set({
                    currentFlashcards: cachedQuiz,
                    isGenerating: false
                });
                return true;
            }

            // 2. If it misses, we need to generate it from scratch using Gemini
            console.log(`[Store:Flashcards] Vault Miss, Synthesizing: ${activeTopic}`);
            const quiz = await generateGeminiQuiz(activeTopic, difficulty, null);

            // 3. Cache it for next time
            await saveQuizToVault(activeTopic, difficulty, quiz);

            set({
                currentFlashcards: quiz,
                isGenerating: false
            });
            return true;

        } catch (error) {
            console.error("Failed to generate flashcards", error);
            set({ isGenerating: false });
            alert(error.message || "Failed to generate flashcards.");
            return false;
        }
    },

    generateAIQuiz: async (topic, difficulty = 'Intermediate', file = null, forceRefresh = false) => {
        const { usageStats, isPremium } = get();
        const today = new Date().toDateString();

        // Reset count if it's a new day
        let currentUsage = usageStats;
        if (usageStats.lastQuizDate !== today) {
            currentUsage = { ...usageStats, quizzesGeneratedToday: 0, lastQuizDate: today };
        }

        // Limit Check
        const isSingularity = get().role === 'singularity';
        if (!isPremium && !isSingularity && currentUsage.quizzesGeneratedToday >= 5) {
            alert("Neural Limit Reached: Free Tier is limited to 5 quiz generations per day. Upgrade to Premium for unlimited mastery.");
            return false;
        }

        set({
            isGenerating: true,
            userTopic: file ? `Document: ${file.name}` : topic,
            currentDifficulty: difficulty,
            currentQuestionIndex: 0,
            score: 0,
            answers: [],
            skillStats: { Syntax: 0, Architecture: 0, Logic: 0, Theory: 0, Security: 0 },
            usageStats: currentUsage
        });

        try {
            // 1. The Safety Audit (The Guardian Layer)
            const auditResult = await guardian.audit(topic);

            if (!auditResult.safe) {
                alert(`Security Protocol: ${auditResult.reason}`);
                set({ isGenerating: false });
                return false;
            }

            let activeTopic = topic;
            if (activeTopic.startsWith("Mastery: ")) activeTopic = activeTopic.replace("Mastery: ", "");

            if (auditResult.redirect) {
                console.log(`[Store] Guardian Redirect Active: ${auditResult.status}`);
                activeTopic = auditResult.redirect;
                set({ userTopic: `Mastery: ${activeTopic}` });
            }

            // 2. Knowledge Vault Check (Optimization)
            if (!forceRefresh && !file) {
                const cachedQuiz = await getQuizFromVault(activeTopic, difficulty);
                if (cachedQuiz) {
                    console.log(`[Store] Knowledge Vault Match: ${activeTopic}`);
                    set({
                        currentQuiz: cachedQuiz,
                        isGenerating: false
                    });

                    // Persist to local
                    localStorage.setItem('quiz_data', JSON.stringify(cachedQuiz));
                    localStorage.setItem('quiz_topic', get().userTopic);
                    localStorage.setItem('quiz_diff', difficulty);
                    localStorage.setItem('quiz_index', '0');
                    localStorage.setItem('quiz_score', '0');
                    localStorage.setItem('quiz_answers', '[]');
                    return true;
                }
            }

            // 3. Generation logic
            const quiz = await generateGeminiQuiz(activeTopic, difficulty, file);

            // Cache to Knowledge Vault
            if (!file) {
                await saveQuizToVault(activeTopic, difficulty, quiz);
            }

            // Update Usage
            const updatedUsage = {
                ...get().usageStats,
                quizzesGeneratedToday: get().usageStats.quizzesGeneratedToday + 1
            };

            set({
                currentQuiz: quiz,
                isGenerating: false,
                usageStats: updatedUsage
            });

            // Persist new quiz and usage
            localStorage.setItem('quiz_data', JSON.stringify(quiz));
            localStorage.setItem('usage_stats', JSON.stringify(updatedUsage));

            // [SCALE OPTIMIZATION] Defer usage sync to avoid document locks. 
            // We rely on localStorage for immediate rate limiting, and sync 
            // back to the cloud only at the end of a session or periodically.
            if (get().user) {
                console.log("[Scale] Deferred usage stats sync to prevent write contention.");
                // Sync is handled later in submitAnswer
            }

            localStorage.setItem('quiz_topic', get().userTopic);
            localStorage.setItem('quiz_diff', difficulty);
            localStorage.setItem('quiz_index', '0');
            localStorage.setItem('quiz_score', '0');
            localStorage.setItem('quiz_answers', '[]');

            return true;
        } catch (error) {
            set({ isGenerating: false });
            alert(error.message || "Failed to generate quiz. The Neural Core is currently experiencing heavy load.");
            return false;
        }
    },

    submitAnswer: async (answer) => {
        const { currentQuestionIndex, score, answers, currentQuiz, skillStats, user } = get();
        const currentQuestion = currentQuiz[currentQuestionIndex];
        const isCorrect = answer === currentQuestion.answer;

        const updatedStats = { ...skillStats };
        if (isCorrect) {
            updatedStats[currentQuestion.category] = (updatedStats[currentQuestion.category] || 0) + 1;
        }

        const newAnswers = [...answers, {
            questionId: currentQuestion.id,
            selected: answer,
            correct: currentQuestion.answer,
            isCorrect
        }];

        const isFinished = newAnswers.length === currentQuiz.length;

        set({
            score: isCorrect ? score + 1 : score,
            answers: newAnswers,
            skillStats: updatedStats
        });

        // Persist progress
        localStorage.setItem('quiz_score', (isCorrect ? score + 1 : score).toString());
        localStorage.setItem('quiz_answers', JSON.stringify(newAnswers));

        // Sync to Firestore if logged in
        if (user) {
            try {
                // [SCALE OPTIMIZATION] Only write to DB when the quiz is fully complete
                // Prevents 10 writes per quiz down to 1 write per quiz per user.
                if (isFinished) {
                    const finalScore = isCorrect ? score + 1 : score;
                    const percentage = Math.round((finalScore / currentQuiz.length) * 100);

                    const newTotalQuizzes = get().globalStats.totalQuizzes + 1;
                    const newAverageScore = Math.round(((get().globalStats.averageScore * get().globalStats.totalQuizzes) + percentage) / newTotalQuizzes);

                    const updatedGlobalStats = {
                        totalQuizzes: newTotalQuizzes,
                        averageScore: newAverageScore
                    };

                    set({ globalStats: updatedGlobalStats });
                    localStorage.setItem('global_stats', JSON.stringify(updatedGlobalStats));

                    await syncSessionData(user.uid, {
                        skillStats: updatedStats,
                        usageStats: get().usageStats,
                        globalStats: updatedGlobalStats
                    });
                    await saveQuizToHistory(user.uid, {
                        topic: get().userTopic,
                        score: finalScore,
                        total: currentQuiz.length,
                        difficulty: get().currentDifficulty,
                        answers: newAnswers // [SCALE OPTIMIZATION] Embed flat array inside history doc
                    });
                }
            } catch (error) {
                console.error("Store: DB Sync Failed", error);
            }
        }

        // We stop auto-advancing here to let user read explanations
        // If it's the last question, we still do the milestone logic
        if (!isFinished) return;

        // Milestone completion check
        const finalScore = isCorrect ? score + 1 : score;
        const totalQuestions = currentQuiz.length;

        if (totalQuestions === 0) return;
        const percentage = (finalScore / totalQuestions) * 100;

        // If it's a roadmap assessment and score >= 70%
        const activeNodeId = get().activeRoadmapNode;
        const activeRoadmapId = get().activeRoadmapId;

        if (activeNodeId && activeRoadmapId && percentage >= 70) {
            const currentProgress = { ...get().roadmapProgress };
            if (!currentProgress[activeRoadmapId]) currentProgress[activeRoadmapId] = [];
            if (!currentProgress[activeRoadmapId].includes(activeNodeId)) {
                currentProgress[activeRoadmapId].push(activeNodeId);
                set({ roadmapProgress: currentProgress });
                localStorage.setItem('roadmap_progress', JSON.stringify(currentProgress));

                // Sync to Cloud
                if (user) {
                    try {
                        const { saveRoadmapProgress } = await import('../services/dbService');
                        await saveRoadmapProgress(user.uid, currentProgress);
                    } catch (e) { console.error("Cloud Roadmap Sync Failed", e); }
                }
            }
        }
    },

    setActiveRoadmap: (roadmapId, nodeId) => {
        set({ activeRoadmapId: roadmapId, activeRoadmapNode: nodeId });
        localStorage.setItem('active_roadmap_id', roadmapId);
        localStorage.setItem('active_roadmap_node', nodeId);
    },

    resetRoadmapProgress: async (roadmapId) => {
        const { roadmapProgress, user } = get();
        const newProgress = { ...roadmapProgress };
        delete newProgress[roadmapId];

        set({ roadmapProgress: newProgress });
        localStorage.setItem('roadmap_progress', JSON.stringify(newProgress));

        if (user) {
            try {
                const { saveRoadmapProgress } = await import('../services/dbService');
                await saveRoadmapProgress(user.uid, newProgress);
            } catch (e) {
                console.error("Store: Cloud Reset Failed", e);
            }
        }
    },

    setRoadmapLevel: async (roadmapId, level) => {
        const { roadmapLevels, user } = get();

        const newLevels = { ...roadmapLevels, [roadmapId]: level };

        set({
            roadmapLevels: newLevels
        });

        localStorage.setItem('roadmap_levels', JSON.stringify(newLevels));

        // Sync to cloud
        if (user) {
            try {
                const { saveUserStats } = await import('../services/dbService');
                // Level can be saved to user profile or a specific collection in the future
            } catch (e) {
                console.error("Store: Cloud Level Sync Failed", e);
            }
        }
    },

    // Auth Actions
    initAuth: () => {
        return subscribeToAuthChanges(async (user) => {
            if (user) {
                try {
                    const { getUserStats, getRoadmapProgress, getUsageStats, ensureUserInitialized } = await import('../services/dbService');

                    // 1. Ensure user has a profile record
                    const profile = await ensureUserInitialized(user);

                    // 2. Load all other cloud data
                    const [cloudStats, cloudRoadmap, usageInfo] = await Promise.all([
                        getUserStats(user.uid),
                        getRoadmapProgress(user.uid),
                        getUsageStats(user.uid)
                    ]);

                    const newState = { user, isAuthLoading: false };
                    if (cloudStats) {
                        newState.skillStats = cloudStats.skillStats;
                        newState.globalStats = cloudStats.globalStats || { totalQuizzes: 0, averageScore: 0 };
                        localStorage.setItem('global_stats', JSON.stringify(newState.globalStats));
                    }
                    if (cloudRoadmap) {
                        newState.roadmapProgress = cloudRoadmap;
                        localStorage.setItem('roadmap_progress', JSON.stringify(cloudRoadmap));
                    }
                    if (usageInfo) {
                        if (usageInfo.usageStats) {
                            newState.usageStats = usageInfo.usageStats;
                            localStorage.setItem('usage_stats', JSON.stringify(usageInfo.usageStats));
                        }
                        newState.isPremium = usageInfo.isPremium;
                        newState.role = usageInfo.role || 'learner';
                        localStorage.setItem('is_premium', JSON.stringify(usageInfo.isPremium));
                    }
                    set(newState);
                } catch (error) {
                    console.error("Store: Cloud sync failed", error);
                    set({ user, isAuthLoading: false });
                }
            } else {
                set({ user: null, isAuthLoading: false });
            }
        });
    },

    signIn: async () => {
        try {
            const user = await loginWithGoogle();
            set({ user });
        } catch (error) {
            console.error("Store: Sign In Error", error);
        }
    },

    signUpWithEmail: async (email, password) => {
        try {
            const result = await registerWithEmail(email, password);
            set({ user: result.user });
            return { success: true };
        } catch (error) {
            console.error("Store: Register Error", error);
            return { success: false, error: error.message };
        }
    },

    signInWithEmail: async (email, password) => {
        try {
            const result = await loginWithEmail(email, password);
            set({ user: result.user });
            return { success: true };
        } catch (error) {
            console.error("Store: Login Error", error);
            return { success: false, error: error.message };
        }
    },

    nextQuestion: () => {
        const { currentQuestionIndex, currentQuiz } = get();
        if (currentQuestionIndex + 1 < currentQuiz.length) {
            const nextIndex = currentQuestionIndex + 1;
            set({ currentQuestionIndex: nextIndex });
            localStorage.setItem('quiz_index', nextIndex.toString());
        }
    },

    signOut: async () => {
        await logout();
        set({
            user: null,
            role: 'learner',
            currentQuiz: [],
            answers: [],
            score: 0,
            skillStats: { Syntax: 0, Architecture: 0, Logic: 0, Theory: 0, Security: 0 },
            roadmapProgress: {},
            roadmapLevels: {},
            activeRoadmapId: null,
            activeRoadmapNode: null
        });

        // Clear all persistent session data
        const keysToRemove = [
            'quiz_data', 'quiz_topic', 'quiz_diff', 'quiz_index',
            'quiz_score', 'quiz_answers', 'roadmap_progress', 'roadmap_levels',
            'active_roadmap_id', 'active_roadmap_node', 'global_stats'
        ];
        keysToRemove.forEach(k => localStorage.removeItem(k));
    },

    reset: () => {
        set({
            currentQuiz: [],
            currentQuestionIndex: 0,
            score: 0,
            answers: [],
            userTopic: '',
            skillStats: { Syntax: 0, Architecture: 0, Logic: 0, Theory: 0, Security: 0 }
        });

        const keysToRemove = [
            'quiz_data', 'quiz_topic', 'quiz_diff', 'quiz_index',
            'quiz_score', 'quiz_answers'
        ];
        keysToRemove.forEach(k => localStorage.removeItem(k));
    },

    updatePassword: async (newPassword) => {
        const { updateUserPassword } = await import('../services/authService');
        return updateUserPassword(newPassword);
    },

    updateProfile: async (displayName) => {
        const { updateUserProfile } = await import('../services/authService');
        await updateUserProfile({ displayName });
        set({ user: { ...get().user, displayName } });
    },

    deleteAccount: async () => {
        const { deleteUserAccount } = await import('../services/authService');
        await deleteUserAccount();
        get().signOut();
    },

    // Improvement Room Actions
    startForge: (category) => {
        // Mocking room data for now - in a real app, this would be AI-generated via geminiService
        const mockForgeData = {
            Deconstruction: `The concept of "${category}" relies on three core ideas: simple logic, keeping state, and handling errors. When these break, your understanding might slip.`,
            Analogy: `Think of "${category}" as the foundation of a house. If the foundation isn't solid, the whole house (complex stuff) will shake.`,
            Puzzle: `Which of these three ideas is most important for making sure the system stays stable?`
        };

        set({
            isForgeActive: true,
            forgeConcept: category,
            forgeStep: 1,
            forgeData: mockForgeData
        });
    },

    nextForgeStep: () => {
        const { forgeStep } = get();
        if (forgeStep < 3) {
            set({ forgeStep: forgeStep + 1 });
        } else {
            get().exitForge();
        }
    },

    exitForge: () => {
        set({
            isForgeActive: false,
            forgeConcept: null,
            forgeStep: 1,
            forgeData: null
        });
    },

    setPremium: async (status) => {
        set({ isPremium: status });
        localStorage.setItem('is_premium', JSON.stringify(status));
        if (get().user) {
            try {
                const { doc, updateDoc, db } = await import("../services/firebase");
                await updateDoc(doc(db, "users", get().user.uid), { isPremium: status });
            } catch (e) {
                console.warn("Store: Premium Sync Failed", e);
            }
        }
    },

    toggleScenarioMode: () => {
        const newMode = !get().isScenarioMode;
        set({ isScenarioMode: newMode });
        localStorage.setItem('is_scenario_mode', JSON.stringify(newMode));
    }
}));
